version: '3'

services:
  web:
    build: .  # Build the Flask app image from the Dockerfile in the current directory
    ports:
      - "8000:8000"  # Expose port 8000 to access the app from the host machine
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    #environment:
     # - FLASK_APP=app.py  # Set environment variables for Flask
    # - FLASK_ENV=development  # Run Flask in development mode
